version: '3.8'
services:
  pgadmin:
    image: dpage/pgadmin4:8.3
    restart: "no"
    ports:
      - "5050:80" # Cambiar si deseas otro puerto
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - postgis_postgis
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin

networks:
  postgis_postgis:
    external: true
